### ISSUE TITLE
normalise_data error: Error in solve.default(ac %*% t(ac))

### ISSUE THREAD

**Issue by tmmack** [mtrussart/CytofRUV#25]
When I run the normalise_data step I get the following error:

Error in solve.default(ac %*% t(ac)) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0

Does anyone know what this means or how to fix it?  

Thanks!

**Comment by mtrussart** [comment]
Hi,
I think it is related to your data design and your data matrix. Could you please share the details about the matrix design (conditions, batch...) and the replicated samples ?

Best wishes,
Marie
