### ISSUE TITLE
transformation after CytofRUV normalization??

### ISSUE THREAD

**Issue by Sudhirkumarchauhan** [mtrussart/CytofRUV#26]
Hi,
I see there is a difference in how the data look in flowjo after normalization with CytofRUV (please see the file attached)? What may be causing that?
Also few more questions-
1. Flowjo output files are linear. Does Cytofruv applies ArcSinh transformation to the fcs files before normalization or should I do it myself before running it through Cytofruv.
2. Regarding normalized fcs files from Cytofruv, are they ArcSinh transformed already?

Thanks for any inputs!
Sudhir

[Before-after Cytofruv.pptx](https://github.com/mtrussart/CytofRUV/files/6062383/Before-after.Cytofruv.pptx)

**Comment by mtrussart** [comment]
Dear Sudhir,

Yes as we explained with more details in the manuscript, the data has been arcsinh transformed with a cofactor of 5 and then batch-normalised by CytofRUV. You do not need to specify it as it is being applied in our package. 
That means that if you compare the unadjusted data with the normalised data, it is expected to look different to make the distributions of markers more uniform across batches. 
Marie

**Comment by mtrussart** [comment]
Sorry I have closed this issue by mistake. In the picture you send I suspect the data "Before" has been log-transformed in FlowJo, is that right?

**Comment by Sudhirkumarchauhan** [comment]
Thanks for the information.  This is how I did it.
1. Exported files as fcs 3.0 from flowjo, that I believe should export the data in linear format without any transformation.
2. these exported files were subjected to Cytofruv and normalized using internal control for each of the 4 runs.
3. then both, input file to Cytofruv and cytof normalized files were loaded to flowjo, in the attach you will see both are ArcSinh transformed.

I understand that marker distribution will change due to normalization process, but if you see the plots for before-Cytofruv files for all 4 runs, markers became quite condensed at axis after normalization.


Thanks again for help!
Sudhir
[Before-after Cytofruv_V2.pptx](https://github.com/mtrussart/CytofRUV/files/6069468/Before-after.Cytofruv_V2.pptx)

**Comment by mtrussart** [comment]
Hi,

You do not need to apply another arcsinh again to the normalised data in FlowJo.
What I can suggest is that if you are more used to look at the log-transformed data in FlowJo you could apply an inverse arcsinh transformation on the normalised data and then look at it in FlowJo with the log-transformation. Is that what you are interested in? 
If you look at the data in R and compare the normalised data and the raw data after arcsinh tranformation with cofactor 5, it should not look so different, did you try that?
