### ISSUE TITLE
Error with installing the packages 

### ISSUE THREAD

**Issue by elensyri** [mtrussart/CytofRUV#27]
Hi there trying to download this and get an error message: Error in utils::download.file(url, path, method = method, quiet = quiet,  : download from 'https://api.github.com/repos/mtrussart/CytofRUV/tarball/HEAD' failed

Can you please advice a solution? 
Thanks a lot.

**Comment by mtrussart** [comment]
Hi,

Thanks for reaching out. Could you please share the command that you have used to download the package and also your R session info?
It's difficult for me to help you otherwise.

Marie

**Comment by kilejonez** [comment]
Hi--

I have the exact same problem when trying to load the package. Here is my R session info:

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

Here is the download command that I ran along with the error message:

> install_github('mtrussart/CytofRUV')
Downloading GitHub repo mtrussart/CytofRUV@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/mtrussart/CytofRUV/tarball/HEAD' failed

I'm newer to R so this could totally be a dumb error on my part. My apologies if it is.

**Comment by mtrussart** [comment]
Hi, I am not sure what is happening I have tried again today to launch this command and I do not get any errors. Could you please send me your R session info. Do you have an updated version of devtools?

**Comment by mtrussart** [comment]
Are you using Windows?

**Comment by SamGG** [comment]
Hi Marie,
It's written `Platform: x86_64-apple-darwin17.0 (64-bit)`

**Comment by mtrussart** [comment]
Yes sorry you are right, I found similar issues saying it might be related to windows or a proxy server. Are you able to install  other repositories, is it happening only with my repo?

**Comment by kilejonez** [comment]
Thanks so much for your quick response. It looks like it's an issue with my machine. One of my other colleagues with a Mac running the same version of R was able to download it fine. I'll try and troubleshoot on my end.

Thanks again.

**Comment by mtrussart** [comment]
No worries, hope you can sort it out!
