### ISSUE TITLE
Trouble installing CytofRUV

### ISSUE THREAD

**Issue by northern-soul-marie91** [mtrussart/CytofRUV#30]
Hi Marie,

I am trying to install CytofRUV and getting the following error:
> remotes::install_github("mtrussart/CytofRUV")
Downloading GitHub repo mtrussart/CytofRUV@HEAD
Skipping 10 packages not available: ComplexHeatmap, limma, S4Vectors, SingleCellExperiment, ConsensusClusterPlus, SummarizedExperiment, FlowSOM, flowCore, CATALYST, Biobase
✓  checking for file ‘/private/var/folders/m6/k46f7jvn425_jhm6jwc28dq80000gn/T/RtmpIQisKb/remotes5564306237e2/mtrussart-CytofRUV-e0cc651/DESCRIPTION’ ...
─  preparing ‘CytofRUV’:
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘CytofRUV/tests’
─  building ‘CytofRUV_0.1.tar.gz’
   
* installing *source* package ‘CytofRUV’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
Execution halted
ERROR: lazy loading failed for package ‘CytofRUV’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/CytofRUV’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/m6/k46f7jvn425_jhm6jwc28dq80000gn/T//RtmpIQisKb/file556442ef3f/CytofRUV_0.1.tar.gz’ had non-zero exit status

Session info:
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.2.1

Please could you help.

Best wishes,
(another) Marie

**Comment by mtrussart** [comment]
Hi Marie,

I am not sure what could be the problem, it says "Skipping 10 packages not available: ComplexHeatmap, limma, S4Vectors, SingleCellExperiment, ConsensusClusterPlus, SummarizedExperiment, FlowSOM, flowCore, CATALYST, Biobase".  Did you manage to install all libraries dependencies?

It seems it could be related to the ComplexHeatmap package, have a look here: https://github.com/jokergoo/ComplexHeatmap/issues/685 

Best wishes,
Marie

**Comment by northern-soul-marie91** [comment]
Hi Marie,

Thanks for replying so quickly. It was an issue with ComplexHeatmap as I did not have XQuartz installed. I have now managed to install CytofRUV successfully.

Best wishes,
Marie

**Comment by mick42-star** [comment]
Hi Marie,
I had same issue when installing CytoRUV however my ComplexHeatmap works fine, What else could be the reasons？

> library(devtools)
Loading required package: usethis
> install_github('mtrussart/CytofRUV')
Downloading GitHub repo mtrussart/CytofRUV@HEAD
Skipping 10 packages not available: ComplexHeatmap, limma, S4Vectors, SingleCellExperiment, ConsensusClusterPlus, SummarizedExperiment, FlowSOM, flowCore, CATALYST, Biobase
✔  checking for file 'C:\Users\AppData\Local\Temp\RtmpWm3AFB\remotes59b478c76f5f\mtrussart-CytofRUV-7088af8/DESCRIPTION' ...
─  preparing 'CytofRUV':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'CytofRUV/tests'
─  building 'CytofRUV_0.1.tar.gz'
   
Installing package into ‘C:/Users/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependencies 'CATALYST', 'flowCore', 'FlowSOM', 'ConsensusClusterPlus', 'SingleCellExperiment' are not available for package 'CytofRUV'
* removing 'C:/Users/AppData/Local/R/win-library/4.2/CytofRUV'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/AppData/Local/Temp/RtmpWm3AFB/file59b416cc5061/CytofRUV_0.1.tar.gz’ had non-zero exit status
> library(ComplexHeatmap)
Loading required package: grid
========================================
ComplexHeatmap version 2.12.1
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://jokergoo.github.io/ComplexHeatmap-reference

If you use it in published research, please cite either one:
- Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
    genomic data. Bioinformatics 2016.
- Gu, Z. Complex Heatmap Visualization. iMeta 2022.


The new InteractiveComplexHeatmap package can directly export static 
complex heatmaps into an interactive Shiny app with zero effort. Have a try!

This message can be suppressed by:
  suppressPackageStartupMessages(library(ComplexHeatmap))
========================================

**Comment by SamGG** [comment]
Hi,
This is not the same error although the same warning message is issued. The error is specifically that the dependencies are not installed. So you should have opened a new issue instead of commenting a closed issue. Nevertheless, what you should do is to install the missing dependencies using bioconductor.
Best.

**Comment by mick42-star** [comment]
Thanks. The problem has been solved.
