### ISSUE TITLE
dimension of the unwanted variation, k

### ISSUE THREAD

**Issue by jsim91** [mtrussart/CytofRUV#35]
Hello CytofRUV team. After reading through the CytofRUV publication and `normalise_data` documentation it's still not clear to me how to interpret the `k` argument in `normalise_data`. Although there is no default value for this argument, a value of 5 is used in the vignette. Is this a value that just generally work? Thanks!

**Comment by mtrussart** [comment]
Hi, 
Thanks for your question and for reaching out.
k=5 was used in the vignette as an example.  The dimension (k) of the unwanted variation needs to be determined through a careful optimisation process. To find a good value for k, we repeat the analysis with different values of k and then evaluate the quality of each result using our diagnostic plots and the corresponding summary statistics described in our manuscript.

**Comment by jsim91** [comment]
Thank you for the response. In your experience is there a range of values that might contain the optimal value. If it helps, I have a data set of 161 experimental samples across 20 different runs using a 30 parameter panel.

**Comment by mtrussart** [comment]
As I said in the previous message, it's hard to answer this question without looking at the dataset and evaluate the quality of the normalisation with the corresponding summary statistics described in our manuscript.
