### ISSUE TITLE
normalise_data error "Error in norm_cells[inds, c(data$lineage_markers, data$functional_markers)] :    subscript out of bounds"

### ISSUE THREAD

**Issue by shanh1** [mtrussart/CytofRUV#37]
Hi there!

I hope you are well.

I have an issue when I get to the normalisation stage for my data. I get the following error:

`Error in norm_cells[inds, c(data$lineage_markers, data$functional_markers)] : 
  subscript out of bounds` 

Everything has worked well until this stage. All of the antigens correspond with the .fcs files, so I am not sure where the error is. I have also tried normalising without time.

My metadata and antibody panel tables are attached.

[Debarcoded_T_NK_panel.xlsx](https://github.com/mtrussart/CytofRUV/files/10849877/Debarcoded_T_NK_panel.xlsx)
[Batch_Correction_MD.xlsx](https://github.com/mtrussart/CytofRUV/files/10849878/Batch_Correction_MD.xlsx)

Thank you kindly!

Shan

**Comment by mtrussart** [comment]
Hi Shan,

Thanks for reaching out. 
I suggest you first check that all the protein markers names that you listed in the Panel excel file in the fcs_colname (Yb172Di,Cd106Di..) have the exact same corresponding names in your .FCS files. I understood from your message that you already checked that?
Also you said that you have tried normalising without time. What do you mean by that, do you have a "Time" column in the .fcs files?

Marie

**Comment by shanh1** [comment]
Hi Marie,

Thank you kindly for your response.

Yes, all the protein marker names in the panel correspond with the .fcs files.

I believe in a previous issue opened there was a script attached where the data could be normalised without time, so I also tried this. 

I am an R novice so I am not entirely sure how I would check if my files have a "time" column.

Shan

**Comment by mtrussart** [comment]
Yes that's right I made another script for that person because in this case the .fcs files did not have a "time" column. 
You should load the .fcs file in R using for example readFCS function (https://rdrr.io/bioc/flowCore/man/read.FCS.html).

Regarding the error you are getting, I would recommend you follow each step of the vignette before running the norm function.
Marie
