### ISSUE TITLE
normalise_data crashes with "subscript out of bounds"

### ISSUE THREAD

**Issue by yvytan** [mtrussart/CytofRUV#38]
Dear all, 

I am having trouble with running this code as getting the error below: 

normalise_data(data=data,raw_data=raw_data,rep_samples=rep_samples, norm_clusters=cluster_list_rep_samples, k=k_value, num_clusters=clusters_nb,wd_data=wd_data,dir_norm_data=dir_name_norm_data)

Error in expr[, all_fullname_markers] : subscript out of bounds

Could you please kindly advise?

**Comment by mtrussart** [comment]
Hi,

This issue has been already reported and I have explained in previous issues what to check in such cases. Could you please check the previous issues to see if that resolves your issues:

https://github.com/mtrussart/CytofRUV/issues/37 
https://github.com/mtrussart/CytofRUV/issues/6

Thanks a lot,
Marie

**Comment by yvytan** [comment]
Hi Marie, 

I had already checked the previous issues and all my files (FCS, md and panel) match each other. Yet I am still encountering the same error. Could you please kindly suggest? I have attached my files in the link below for your reference. 

https://www.dropbox.com/sh/hxur1w8lk1szjk4/AABEb06SSghyZ93rodXD9cdla?dl=0

**Comment by SamGG** [comment]
Hi Yvonne,
Only one file in batch 3? Don't know if it is a problem or not.
Best.

**Comment by yvytan** [comment]
Hi would that affect it? Do I have to run CytofRuv across all 200samples in one go?? 
I have 10 batches with 20samples in each batch. I am correcting the batch effect based on my experimental hypotheses: 
- condition “early” versus condition “refractory “
- Condition “healthy” versus condition “early “

**Comment by yvytan** [comment]
Dear all, I have now ran all my samples (each batch has the same number of samples)  through CyTOFRUV. However, I am still experiencing the same error message "Error in expr [, all_fullname_makers] : subscript out of bounds. 
Thus I don't think the issue is due to unequal distribution of sample per batch as suggested by [SamGG] in the earlier comment. (https://github.com/SamGG)

Any advice please?

**Comment by mtrussart** [comment]
Hi,

Sorry for the delay I was on holidays, could you please share again the files in the Dropbox I am not able to download it, it says it's been deleted. It will be great if you share all the files so that I can reproduce the error and give suggestions.

Thanks a lot,
Marie

**Comment by yvytan** [comment]
Hi Marie, 

Please find link below for the files
https://www.dropbox.com/sh/hxur1w8lk1szjk4/AABEb06SSghyZ93rodXD9cdla?dl=0

**Comment by mtrussart** [comment]
Hi,

I have tested the files you shared with me and the issue is that you do not have a "Time" column in the fcs files. As I mentioned before, this error was previously raised and I have provided a script with an alternative normalise_data function. 
Please refer to the details here:
https://github.com/mtrussart/CytofRUV/issues/6

Let me know if you have any further issue.

Best wishes,
Marie
