### ISSUE TITLE
launch_Shiny() with Error in checkboxGroupInput

### ISSUE THREAD

**Issue by Sudhirkumarchauhan** [mtrussart/CytofRUV#4]
Hi,
I am getting following error, when launching Shiny. What could be the reason?

Thanks,
Sudhir
> ################
> library(CytofRUV)
> launch_Shiny()
Loading required package: shiny
Warning: package ‘shinydashboard’ was built under R version 3.6.3

Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box

Don't forget that shinyjs can also be used in Rmd documents!

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

Warning: package ‘purrr’ was built under R version 3.6.3
Warning: package ‘CATALYST’ was built under R version 3.6.3
Error in checkboxGroupInput("checkBox_TSNE", "Select Up To 10 SampleIDs",  : 
  object 'sampleID_sorted' not found
>

**Comment by mtrussart** [comment]
Hi,

Yes the reason is that you need to define a few parameters like sampleID_sorted in order to launch the Shiny App. As explained in the vignette, you need to run the whole chunk from 96 to 134, where you are defining some parameters like the sampleID_sorted line 111 to run the last command launch_Shiny().
I copy below the code you need to run:

```{r ShinyApp on the raw data,eval=FALSE}
  ## Define parameters to use for R-Shiny
  daf=data$daf
  md=data$md
  seed=1234
  # Number of cells for diagnostic plots marker specific
  n_subset_marker_specific <- 10000
  # Define type of markers
  daf_type <- daf[SingleCellExperiment::rowData(daf)$marker_class=="type", ]
  daf_state <- daf[SingleCellExperiment::rowData(daf)$marker_class=="state", ]
  sub_daf_state <- daf_state[, sample(ncol(daf_state), n_subset_marker_specific)]
  sub_daf_type <- daf_type[, sample(ncol(daf_type), n_subset_marker_specific)]
  # Define batch
  batch_ids <- is.factor(rep(md$batch, nrow(daf)))
  sampleID_sorted <- md$sample_id[order(md$patient_id)]
  
  # Running Dimension Reduction -> TSNE & UMAP
  set.seed(seed)
  # Number of cells for tSNE plots marker specific
  TSNE_subset <- 2000
  print("Running TSNE")
  daf <- CATALYST::runDR(daf, dr = "TSNE", cells = TSNE_subset)
  
  # Number of cells for UMAP plots marker specific
  UMAP_subset <- 2000
  print("Running UMAP")
  daf <- runDR(daf, "UMAP", cells = UMAP_subset)
  
  ## Launch Shiny
  # For a subset of the data, define the number of cells for diagnostic plots
  n_subset <- 5000
  sub_daf <- daf[, sample(ncol(daf), n_subset)]
  
  # # For the full dataset: 
  # sub_daf <- daf
  panel=data$panel
  
  CytofRUV::launch_Shiny()
```

**Comment by Sudhirkumarchauhan** [comment]
Thank you very much :)
Sudhir
